In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4])

Criando um array de multidimensoes com o numpy

In [5]:
b = np.array([(1, 2, 3),(4, 5, 6), (7, 8, 9)])

In [6]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
c = np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
b.max()

9

In [9]:
b.min()

1

In [10]:
b.sum()

45

In [11]:
b.mean()

5.0

In [12]:
b.std()

2.581988897471611

In [13]:
import pandas as pd

In [15]:
 df = pd.read_csv('/Users/rcharles/Desktop/python-ml/pythonmachinelearning/Studio Ghibli.csv')

In [18]:
df.head(10)

Name  Year              Director  \
0            When Marnie Was There\n       (2014)  2014  Hiromasa Yonebayashi   
1  The Tale of The Princess Kaguya\n       (2013)  2013         Isao Takahata   
2                   The Wind Rises\n       (2013)  2013        Hayao Miyazaki   
3            From Up on Poppy Hill\n       (2011)  2011         Goro Miyazaki   
4     The Secret World of Arrietty\n       (2010)  2010  Hiromasa Yonebayashi   
5                            Ponyo\n       (2008)  2008        Hayao Miyazaki   
6                      Ocean Waves\n       (1994)  1994      Tomomi Mochizuki   
7              Tales from Earthsea\n       (2006)  2006         Goro Miyazaki   
8                   Only Yesterday\n       (1991)  1991         Isao Takahata   
9                    Spirited Away\n       (2001)  2001        Hayao Miyazaki   

          Screenplay          Budget        Revenue    Genre 1    Genre 2  \
0   Joan G. Robinson  $1150000000.00   $34949567.00  Animation      Drama   
1     Riko Sakaguchi    $49300000.00   $24366656.00  Animation      Drama   
2        Tatsuo Hori    $30000000.00  $117932401.00      Drama  Animation   
3     Hayao Miyazaki    $22000000.00   $61037844.00  Animation      Drama   
4        Mary Norton    $23000000.00  $149480483.00    Fantasy  Animation   
5                NaN    $34000000.00  $202404009.00  Animation    Fantasy   
6       Saeko Himuro     $5000000.00     $100000.00  Animation      Drama   
7  Ursula K. Le Guin    $22000000.00   $68625104.00  Animation    Fantasy   
8                NaN     $2500000.00     $473110.00  Animation      Drama   
9                NaN    $19000000.00  $274925095.00  Animation     Family   

     Genre 3 Duration  
0        NaN   1h 43m  
1    Fantasy   2h 17m  
2    Romance    2h 6m  
3        NaN   1h 31m  
4     Family   1h 34m  
5     Family   1h 40m  
6    Romance   1h 12m  
7  Adventure   1h 55m  
8    Romance   1h 59m  
9    Fantasy    2h 5m

In [19]:
df_2 = pd.read_csv('/Users/rcharles/Desktop/python-ml/pythonmachinelearning/athlete_events.csv')

In [20]:
df_2.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [25]:
df_2[:]

ID                      Name Sex   Age  Height  Weight  \
0            1                 A Dijiang   M  24.0   180.0    80.0   
1            2                  A Lamusi   M  23.0   170.0    60.0   
2            3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN   
3            4      Edgar Lindenau Aabye   M  34.0     NaN     NaN   
4            5  Christine Jacoba Aaftink   F  21.0   185.0    82.0   
...        ...                       ...  ..   ...     ...     ...   
271111  135569                Andrzej ya   M  29.0   179.0    89.0   
271112  135570                  Piotr ya   M  27.0   176.0    59.0   
271113  135570                  Piotr ya   M  27.0   176.0    59.0   
271114  135571        Tomasz Ireneusz ya   M  30.0   185.0    96.0   
271115  135571        Tomasz Ireneusz ya   M  34.0   185.0    96.0   

                  Team  NOC        Games  Year  Season            City  \
0                China  CHN  1992 Summer  1992  Summer       Barcelona   
1                China  CHN  2012 Summer  2012  Summer          London   
2              Denmark  DEN  1920 Summer  1920  Summer       Antwerpen   
3       Denmark/Sweden  DEN  1900 Summer  1900  Summer           Paris   
4          Netherlands  NED  1988 Winter  1988  Winter         Calgary   
...                ...  ...          ...   ...     ...             ...   
271111        Poland-1  POL  1976 Winter  1976  Winter       Innsbruck   
271112          Poland  POL  2014 Winter  2014  Winter           Sochi   
271113          Poland  POL  2014 Winter  2014  Winter           Sochi   
271114          Poland  POL  1998 Winter  1998  Winter          Nagano   
271115          Poland  POL  2002 Winter  2002  Winter  Salt Lake City   

                Sport                                     Event Medal  
0          Basketball               Basketball Men's Basketball   NaN  
1                Judo              Judo Men's Extra-Lightweight   NaN  
2            Football                   Football Men's Football   NaN  
3          Tug-Of-War               Tug-Of-War Men's Tug-Of-War  Gold  
4       Speed Skating          Speed Skating Women's 500 metres   NaN  
...               ...                                       ...   ...  
271111           Luge                Luge Mixed (Men)'s Doubles   NaN  
271112    Ski Jumping  Ski Jumping Men's Large Hill, Individual   NaN  
271113    Ski Jumping        Ski Jumping Men's Large Hill, Team   NaN  
271114      Bobsleigh                      Bobsleigh Men's Four   NaN  
271115      Bobsleigh                      Bobsleigh Men's Four   NaN  

[271116 rows x 15 columns]