In [2]:
import pandas as pd
alunos = { 'Nome' : ['Rodrigo', 'Fernanda', 'Pedro', 'Roberto', 'Carlos'], 
          'Nota': [9, 8.5, 6, 5, 7],
          'Aprovado': ['Sim', 'Sim', 'Não', 'Não', 'Sim']}

Transformar um dicionário em um DF

In [6]:
df = pd.DataFrame(alunos)
df

Nome  Nota Aprovado
0   Rodrigo   9.0      Sim
1  Fernanda   8.5      Sim
2     Pedro   6.0      Não
3   Roberto   5.0      Não
4    Carlos   7.0      Sim

Comando series

Cria um vetor unidimensional

In [7]:
obj1 = pd.Series([2, 6, 67, 8, 100])
obj1

0      2
1      6
2     67
3      8
4    100
dtype: int64

Criar um array com o Numpy

In [14]:
import numpy as np
array1 = np.array([4, 36, 123, 8, 100])
array2 = np.array([(2, 6, 67, 8, 100), (12, 46, 77, 18, 100)])
print(array1)
print(array2)

[  4  36 123   8 100]
[[  2   6  67   8 100]
 [ 12  46  77  18 100]]


Usando o comando series para transformar um array em um vetor.
Não funciona com arrays bidimensionais.

In [18]:
obj2 = pd.Series(array1)
obj2

0      4
1     36
2    123
3      8
4    100
dtype: int32